# Generated by Django 5.0.7 on 2024-08-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resaletransactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resaletransaction',
            name='floor_area_sqm',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
