# Generated by Django 5.0.7 on 2024-08-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postalcodes', '0004_alter_buildinggeometrypolygon_postal_code'),
        ('resaletransactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resaletransaction',
            name='postal_code_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='postalcodes.postalcodeaddress'),
        ),
    ]
