# Generated by Django 5.1 on 2024-09-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resaletransactions', '0002_alter_resaletransaction_postal_code_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resaletransaction',
            old_name='postal_code_id',
            new_name='postal_code_key',
        ),
    ]
