# Generated by Django 5.0.7 on 2024-08-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resaletransactions', '0002_alter_resaletransaction_floor_area_sqm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resaletransaction',
            name='resale_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
