# Generated by Django 5.1 on 2024-09-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resaletransactions', '0003_rename_postal_code_id_resaletransaction_postal_code_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resaletransaction',
            name='block',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='resaletransaction',
            name='street_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
