# Generated by Django 5.1.1 on 2024-09-14 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postalcodes', '0008_alter_buildinggeometrypolygon_postal_code_key'),
        ('resaletransactions', '0004_alter_resaletransaction_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resaletransaction',
            name='postal_code_key',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resaletransactions', to='postalcodes.postalcodeaddress'),
        ),
    ]
