# static list of mrt stations here
LINES= {
    "NSL": {"name": "NORTH-SOUTH LINE", "colour": "d42e12", "rail_type": "MRT"},
    "EWL": {"name": "EAST-WEST LINE", "colour": "009645", "rail_type": "MRT"},
    "CGL": {"name": "EAST-WEST CHANGI LINE", "colour": "009645", "rail_type": "MRT"},
    "NEL": {"name": "NORTH EAST LINE", "colour": "9900aa", "rail_type": "MRT"},
    "CCL": {"name": "CIRCLE LINE", "colour": "fa9e0d", "rail_type": "MRT"},
    "DTL": {"name": "DOWNTOWN LINE", "colour": "005ec4", "rail_type": "MRT"},
    "TEL": {"name": "THOMSON-EAST COAST LINE", "colour": "9D5B25", "rail_type": "MRT"},
    "CRL": {"name": "CROSS ISLAND LINE", "colour": "97C616", "rail_type": "MRT"},
    "CPL": {"name": "CROSS ISLAND PUNGGOL LINE", "colour": "97C616", "rail_type": "MRT"},
    "JRL": {"name": "JURONG REGION LINE", "colour": "0099aa", "rail_type": "MRT"},
    "BPL": {"name": "BUKIT PANJANG LRT", "colour": "768579", "rail_type": "LRT"},
    "SKL": {"name": "SENGKANG LRT", "colour": "768579", "rail_type": "LRT"},
    "PGL": {"name": "PUNGGOL LRT", "colour": "768579", "rail_type": "LRT"}
  }

STATIONS= {
    # EWL
    "PASIR RIS INTERCHANGE": ["EWL", "CRL"],
    "TAMPINES": ["EWL", "DTL"],
    "SIMEI": ["EWL"],
    "TANAH MERAH INTERCHANGE": ["EWL", "CGL"],
    "BEDOK": ["EWL"],
    "KEMBANGAN": ["EWL"],
    "EUNOS": ["EWL"],
    "PAYA LEBAR INTERCHANGE": ["EWL", "CCL"],
    "ALJUNIED": ["EWL"],
    "KALLANG": ["EWL"],
    "LAVENDER": ["EWL"],
    "BUGIS": ["EWL", "DTL"],
    "CITY HALL": ["EWL", "NSL"],
    "RAFFLES PLACE INTERCHANGE": ["EWL", "NSL"],
    "TANJONG PAGAR": ["EWL"],
    "OUTRAM PARK": ["EWL", "NEL", "TEL"],
    "TIONG BAHRU": ["EWL"],
    "REDHILL": ["EWL"],
    "QUEENSTOWN": ["EWL"],
    "COMMONWEALTH": ["EWL"],
    "BUONA VISTA INTERCHANGE": ["EWL", "CCL"],
    "DOVER": ["EWL"],
    "CLEMENTI": ["EWL","CRL"],
    "JURONG EAST INTERCHANGE": ["EWL", "NSL", "JRL"],
    "CHINESE GARDEN": ["EWL"],
    "LAKESIDE": ["EWL"],
    "BOON LAY INTERCHANGE": ["EWL","JRL"],
    "PIONEER": ["EWL"],
    "JOO KOON": ["EWL"],
    "GUL CIRCLE": ["EWL","CRL"],
    "TUAS CRESCENT": ["EWL"],
    "TUAS WEST ROAD": ["EWL"],
    "TUAS LINK": ["EWL"],

# CGL
    "EXPO INTERCHANGE": ["CGL","DTL"],
    "CHANGI AIRPORT": ["CGL"],

# NSL
    "BUKIT BATOK": ["NSL"],
    "BUKIT GOMBAK": ["NSL"],
    "CHOA CHU KANG": ["NSL", "JRL", "BPL"],
    "YEW TEE": ["NSL"],
    "KRANJI": ["NSL"],
    "MARSILING": ["NSL"],
    "WOODLANDS INTERCHANGE": ["NSL", "TEL"],
    "ADMIRALTY": ["NSL"],
    "SEMBAWANG": ["NSL"],
    "CANBERRA": ["NSL"],
    "YISHUN": ["NSL"],
    "KHATIB": ["NSL"],
    "YIO CHU KANG": ["NSL"],
    "ANG MO KIO INTERCHANGE": ["NSL", "CRL"],
    "BISHAN INTERCHANGE": ["NSL", "CCL"],
    "BRADDELL": ["NSL"],
    "TOA PAYOH": ["NSL"],
    "NOVENA": ["NSL"],
    "NEWTON": ["NSL", "DTL"],
    "ORCHARD": ["NSL", "TEL"],
    "SOMERSET": ["NSL"],
    "DHOBY GHAUT INTERCHANGE": ["NSL", "NEL", "CCL"],
    "MARINA BAY": ["NSL", "TEL", "CCL"],
    "MARINA SOUTH PIER": ["NSL"],

# NEL
    "PUNGGOL COAST": ["NEL"],
    "PUNGGOL": ["NEL", "PGL", "CPL"],
    "SENGKANG": ["NEL", "SKL"],
    "BUANGKOK": ["NEL"],
    "HOUGANG INTERCHANGE": ["NEL", "CRL"],
    "KOVAN": ["NEL"],
    "SERANGOON INTERCHANGE": ["NEL", "CCL"],
    "WOODLEIGH": ["NEL"],
    "POTONG PASIR": ["NEL"],
    "BOON KENG": ["NEL"],
    "FARRER PARK": ["NEL"],
    "LITTLE INDIA INTERCHANGE": ["NEL", "DTL"],
    "CLARKE QUAY": ["NEL"],
    "CHINATOWN": ["NEL", "DTL"],
    "HARBOURFRONT INTERCHANGE": ["NEL", "CCL"],

# SKL
    "COMPASSVALE": ["SKL"],
    "RUMBIA": ["SKL"],
    "BAKAU": ["SKL"],
    "KANGKAR": ["SKL"],
    "RANGGUNG": ["SKL"],
    "CHENG LIM": ["SKL"],
    "FARMWAY": ["SKL"],
    "KUPANG": ["SKL"],
    "THANGGAM": ["SKL"],
    "FERNVALE": ["SKL"],
    "LAYAR": ["SKL"],
    "TONGKANG": ["SKL"],
    "RENJONG": ["SKL"],

# PGL
    "COVE": ["PGL"],
    "MERIDIAN": ["PGL"],
    "CORAL EDGE": ["PGL"],
    "RIVIERA": ["PGL","CPL"],
    "KADALOOR": ["PGL"],
    "OASIS": ["PGL"],
    "DAMAI": ["PGL"],
    "SAM KEE": ["PGL"],#! SHOWN AS SUM KEE IN DB
    "TECK LEE": ["PGL"],
    "PUNGGOL POINT": ["PGL"],
    "SAMUDERA": ["PGL"],
    "NIBONG": ["PGL"],
    "SUMANG": ["PGL"],
    "SOO TECK": ["PGL"],

# CCL
    "BRAS BASAH": ["CCL"],
    "ESPLANADE": ["CCL"],
    "PROMENADE": ["CCL", "DTL"],
    "NICOLL HIGHWAY": ["CCL"],
    "STADIUM": ["CCL"],
    "MOUNTBATTEN": ["CCL"],
    "DAKOTA": ["CCL"],
    "MACPHERSON INTERCHANGE": ["CCL", "DTL"],
    "TAI SENG": ["CCL"],
    "BARTLEY": ["CCL"],
    "LORONG CHUAN": ["CCL"],
    "MARYMOUNT": ["CCL"],
    "CALDECOTT INTERCHANGE": ["CCL"],
    "BOTANIC GARDENS": ["CCL", "DTL"],
    "FARRER ROAD": ["CCL"],
    "HOLLAND VILLAGE": ["CCL"],
    "ONE NORTH": ["CCL"],
    "KENT RIDGE": ["CCL"],
    "HAW PAR VILLA": ["CCL"],
    "PASIR PANJANG": ["CCL"],
    "LABRADOR PARK": ["CCL"],
    "TELOK BLANGAH": ["CCL"],
    "KEPPEL": ["CCL"],
    "CANTONMENT": ["CCL"],
    "PRINCE EDWARD ROAD": ["CCL"],
    "BAYFRONT": ["CCL","DTL"],

# DTL
    "BUKIT PANJANG": ["DTL", "BPL"],
    "CASHEW": ["DTL"],
    "HILLVIEW": ["DTL"],
    "HUME": ["DTL"],
    "BEAUTY WORLD": ["DTL"],
    "KING ALBERT PARK": ["DTL","CRL"],
    "SIXTH AVENUE": ["DTL"],
    "TAN KAH KEE": ["DTL"],
    "STEVENS INTERCHANGE": ["DTL", "TEL"],
    "ROCHOR": ["DTL"],
    "DOWNTOWN": ["DTL"],
    "TELOK AYER": ["DTL"],
    "FORT CANNING": ["DTL"],#! IS SHOWN AS RIVER VALLEY IN DB
    "BENCOOLEN": ["DTL"],
    "JALAN BESAR": ["DTL"],
    "BENDEMEER": ["DTL"],
    "GEYLANG BAHRU": ["DTL"],
    "MATTAR": ["DTL"],
    "UBI": ["DTL"],
    "KAKI BUKIT": ["DTL"],
    "BEDOK NORTH": ["DTL"],
    "BEDOK RESERVOIR": ["DTL"],
    "TAMPINES WEST": ["DTL"],
    "TAMPINES EAST": ["DTL"],
    "UPPER CHANGI": ["DTL"],
    "XILIN": ["DTL"],
    "SUNGEI BEDOK": ["DTL", "TEL"],
    
    # TEL
    "WOODLANDS NORTH STATION": ["TEL"],
    "WOODLANDS SOUTH": ["TEL"],
    "SPRINGLEAF": ["TEL"],
    "LENTOR": ["TEL"],
    "MAYFLOWER": ["TEL"],
    "BRIGHTHILL INTERCHANGE": ["TEL","CRL"],
    "UPPER THOMSON": ["TEL"],
    "MOUNT PLEASANT": ["TEL"],
    "NAPIER": ["TEL"],
    "ORCHARD BOULEVARD": ["TEL"],
    "GREAT WORLD": ["TEL"],
    "HAVELOCK": ["TEL"],
    "MAXWELL": ["TEL"],
    "SHENTON WAY": ["TEL"],
    "MARINA SOUTH": ["TEL"],
    "GARDENS BY THE BAY": ["TEL"],
    "FOUNDERS' MEMORIAL": ["TEL"],
    "TANJONG RHU": ["TEL"],
    "KATONG PARK": ["TEL"],
    "TANJONG KATONG": ["TEL"],
    "MARINE PARADE": ["TEL"],
    "MARINE TERRACE": ["TEL"],
    "SIGLAP": ["TEL"],
    "BAYSHORE": ["TEL"],
    "BEDOK SOUTH": ["TEL"],

# BPL
    "SOUTH VIEW": ["BPL"],
    "KEAT HONG": ["BPL"],
    "TECK WHYE": ["BPL"],
    "PHOENIX": ["BPL"],
    "PETIR": ["BPL"],
    "PENDING": ["BPL"],
    "BANGKIT": ["BPL"],
    "FAJAR": ["BPL"],
    "SEGAR": ["BPL"],
    "JELEPANG": ["BPL"],
    "SENJA": ["BPL"],

    # CRL
    "ELIAS": ["CPL"],
    "CHANGI AIRPORT TERMINNAL FIVE": ["CRL", "TEL"],
    "AVIATION PARK": ["CRL"],
    "LOYANG": ["CRL"],
    "PASIR RIS EAST": ["CRL"],
    "TAMPINES NORTH": ["CRL"],
    "DEFU": ["CRL"],
    "SERANGOON NORTH": ["CRL"],
    "TAVISTOCK": ["CRL"],
    "TECK GHEE": ["CRL"],
    "TURF CITY": ["CRL"],
    "MAJU": ["CRL"],
    "WEST COAST": ["CRL"],
    "JURONG LAKE DISTRICT": ["CRL"],
    # 1 STOP HERE
    "JURONG PIER": ["CRL", "JRL"],
    # 2 STOPS BETWEEN JURONG PIER AND GUL CIRCLE

    # JRL
    "CHOA CHU KANG WEST": ["JRL"],
    "TENGAH": ["JRL"],
    "HONG KAH": ["JRL"],
    "CORPORATION": ["JRL"],
    "JURONG WEST": ["JRL"],
    "BAHAR JUNCTION": ["JRL"],
    "GEK POH": ["JRL"],
    "TAWAS": ["JRL"],
    "TENGAH PLANTATION": ["JRL"],
    "TENGAH PARK": ["JRL"],
    "BUKIT BATOK WEST": ["JRL"],
    "TOH GUAN": ["JRL"],
    "JURONG TOWN HALL": ["JRL"],
    "PANDAN RESERVOIR": ["JRL"],
    "ENTERPRISE": ["JRL"],
    "TUKANG": ["JRL"],
    "JURONG HILL": ["JRL"],
    "NANYANG GATEWAY": ["JRL"],
    "NANYANG CRESCENT": ["JRL"],
    "PENG KANG HILL": ["JRL"],
  }