# Generated by Django 5.0.7 on 2024-07-30 13:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postalcodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingGeometryPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=4)),
                ('postal_code', models.CharField(max_length=6)),
                ('building_polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
