# Generated by Django 5.0.7 on 2024-08-09 03:49

import postalcodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postalcodes', '0002_buildinggeometrypolygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalcodeaddress',
            name='postal_code',
            field=models.CharField(validators=[postalcodes.models.postal_code_validation]),
        ),
    ]
