# Generated by Django 5.0.7 on 2024-08-09 03:50

import postalcodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postalcodes', '0003_alter_postalcodeaddress_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinggeometrypolygon',
            name='postal_code',
            field=models.CharField(validators=[postalcodes.models.postal_code_validation]),
        ),
    ]
