# Generated by Django 5.1 on 2024-09-03 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postalcodes', '0005_alter_postalcodeaddress_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinggeometrypolygon',
            name='postal_code_key',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='postalcodes.postalcodeaddress'),
        ),
    ]
