# Generated by Django 5.1 on 2024-09-04 13:52

import postalcodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postalcodes', '0006_buildinggeometrypolygon_postal_code_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinggeometrypolygon',
            name='block',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='buildinggeometrypolygon',
            name='postal_code',
            field=models.CharField(db_index=True, validators=[postalcodes.models.postal_code_validation]),
        ),
    ]
