# Generated by Django 5.1.1 on 2024-09-14 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postalcodes', '0007_alter_buildinggeometrypolygon_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinggeometrypolygon',
            name='postal_code_key',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buildinggeometrypolygons', to='postalcodes.postalcodeaddress'),
        ),
    ]
