# Generated by Django 5.1.2 on 2024-11-15 10:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MrtStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True)),
                ('rail_type', models.CharField(db_index=True, max_length=3)),
                ('ground_level', models.CharField(db_index=True, max_length=11)),
                ('building_polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
