# Generated by Django 5.1.3 on 2024-11-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtstations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=5, unique=True)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='mrtstation',
            name='lines',
            field=models.ManyToManyField(related_name='stations', to='mrtstations.line'),
        ),
    ]
