# Generated by Django 5.1.3 on 2024-11-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrtstations', '0002_line_mrtstation_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='rail_type',
            field=models.CharField(db_index=True, default='MRT', max_length=3),
            preserve_default=False,
        ),
    ]
