# Generated by Django 5.1.1 on 2024-09-14 16:08

import timestamps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Running', max_length=50, validators=[timestamps.models.query_task_status_validation])),
                ('current_task', models.CharField(blank=True, max_length=255, null=True)),
                ('progress', models.FloatField(default=0, validators=[timestamps.models.query_task_progress_validation])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
