# Generated by Django 5.0.7 on 2024-07-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResaleTransaction',
        ),
    ]
