-- DELETE FROM postalcodes_buildinggeometrypolygon WHERE id > 0;
-- ALTER SEQUENCE postalcodes_buildinggeometrypolygon_id_seq RESTART WITH 1;
-- SELECT * FROM postalcodes_buildinggeometrypolygon

SELECT * FROM postalcodes_postalcodeaddress
SELECT * FROM resaletransactions_resaletransaction

SELECT resaletransactions_resaletransaction.id,
	resaletransactions_resaletransaction.town,
	resaletransactions_resaletransaction.block,
	resaletransactions_resaletransaction.street_name,
	postalcodes_postalcodeaddress.postal_code,
	resaletransactions_resaletransaction.storey_range,
	resaletransactions_resaletransaction.floor_area_sqm,
	resaletransactions_resaletransaction.resale_price
FROM resaletransactions_resaletransaction
JOIN postalcodes_postalcodeaddress
ON postalcodes_postalcodeaddress.block = resaletransactions_resaletransaction.block
AND postalcodes_postalcodeaddress.street_name = resaletransactions_resaletransaction.street_name
ORDER BY resaletransactions_resaletransaction.id;